Color card
VitaliiHrozynskyi/superhero-shop pull request #2
Opened 2022-05-20 11:48 UTC by bereg6

Для использования блоку требуется контейнер ограничивающий его размеры. При использовании блоков больше одного, в папку img добавляются картинки, а в массив imgList их названия.                                                                                                      Реализовать задачу математическими методами, так чтобы она совпадала с видом макета, считаю не возможным, т. к. на некоторых изображениях в макете градиент явно не является преобладающим или средним цветом картинки, т. е. он выбран дизайнером на его усмотрение.

2022-05-20 14:39 UTC, VitaliiHrozynskyi requested changes
1. В задаче стоит условие, которое вы выполнили. Дополнительная оптимизация будет плюсом, но не обязательна к исполнению.
2. Все-таки лучше переделать, что-бы картинка изначально указывалась в html.

2022-05-20 14:39 UTC, VitaliiHrozynskyi commented on tech/tech.html
> +    <meta charset="UTF-8" />
Форматирование не входит в задачу.

2022-05-20 14:39 UTC, VitaliiHrozynskyi commented on index.js
> +      src: `./img/${imgList[i]}`,
Очень спорное решение. 

1. Сама картинка может находиться в блок `color-card` вместо массива картинок обращаетесь по картинке в блок `color-card`.
2. Если вы ссылаетесь на картинку - указывайте полный путь к ней, сейчас вы полностью ограничили работу внешними изображениями.

2022-05-20 14:39 UTC, VitaliiHrozynskyi commented on index.js
> +  return el;
Я бы сделал передавал в этот компонент узел с изображением, а возвращал уже блок с расчитанным градиентом.

2022-05-20 14:39 UTC, VitaliiHrozynskyi commented on index.js
> +      function getAverageRGB(imgEl) {
Вынесите эту функцию за пределы `window.addEventlistener`.

2022-05-20 14:39 UTC, VitaliiHrozynskyi commented on style.css
> +.button {
Форматирование кода не входило в задачу.

2022-05-20 14:39 UTC, VitaliiHrozynskyi commented on style.css
> +.button--full {
То-же форматирование (

2022-05-20 14:39 UTC, VitaliiHrozynskyi commented on index.js
> +  if (params.src) {
Если вы создаете изображение из параметров, стоит так-же учесть возможность что параметр src НЕ указан, и возможные реакции на это (например плейсхолдер?)

2022-05-20 14:39 UTC, VitaliiHrozynskyi commented
НЕ УДАЛЯЙТЕ пул реквест. Просто пушьте новые коммиты в ветку.

2022-05-22 12:26 UTC, VitaliiHrozynskyi requested changes

2022-05-22 12:26 UTC, VitaliiHrozynskyi commented on index.js
> +  function getAverageRGB(imgEl) {
Винесіть ще на рівень вище.

2022-05-22 12:26 UTC, VitaliiHrozynskyi commented on index.js
> +function gradientColor(img, gradient) {
не бачу сенсу в цій функції. Перенесіть у функцію `cardGradient` відповідно до коментаря з попереднього ревью

2022-05-23 14:43 UTC, VitaliiHrozynskyi requested changes

2022-05-23 14:43 UTC, VitaliiHrozynskyi commented on index.js
> +    }
перенесіть частину з 76 - 83 в `cardGradient`.

cardGradient(img[i])

2022-05-23 15:50 UTC, VitaliiHrozynskyi requested changes

2022-05-23 15:50 UTC, VitaliiHrozynskyi commented on index.js
> +const img = document.querySelectorAll(".color-card__img");
Шось я оце провтикав (( 

Давайте переробим трохи функцію `cardGradient`, щоб вона робила наступне:
1. Переіменувати на `createColorCard`
2. Отримує дом елемент. 
3. Шукає в цьому дом елементі `.color-card__img`.
4. Далі вже все як зараз.

А потім на `load` 
```
const colorCards  = document.querySelectorAll(".color-card");
for (let i = 0; i < colorCards.length; i++) {
   createColorCard(colorCards[i])
}
```

Це походу останне ))

2022-05-23 16:38 UTC, bereg6 commented on index.js
> +const img = document.querySelectorAll(".color-card__img");
Переробив.

2022-05-23 16:43 UTC, VitaliiHrozynskyi commented on index.js
> +const img = document.querySelectorAll(".color-card__img");
невірно реалізовано. 

Навіщо вам шукати у всіх зображеннях, якщо можна шукати ТІЛЬКИ в блоці який ми наразі обробляємо?

Подивіться на код з блоку лоад і на те, як у вас.

2022-05-23 16:50 UTC, VitaliiHrozynskyi requested changes

2022-05-23 16:50 UTC, VitaliiHrozynskyi commented on index.js
> +    colorCards[i].appendChild(createColorCard(i));
невірно реалізовано.

Подивіться на код з блоку лоад і на те, як у вас.

2022-05-23 16:50 UTC, VitaliiHrozynskyi commented on index.js
> +  const img = document.querySelectorAll(".color-card__img");
Навіщо вам шукати у всіх зображеннях, якщо можна шукати ТІЛЬКИ в блоці який ми наразі обробляємо?

2022-05-23 17:08 UTC, bereg6 commented on index.js
> +const img = document.querySelectorAll(".color-card__img");
Тепер так?

2022-05-23 17:14 UTC, VitaliiHrozynskyi requested changes

2022-05-23 17:14 UTC, VitaliiHrozynskyi commented on index.js
> +  console.log(height);
Ви ніби прямо не хочере завершувати цю задачу? )))

2022-05-23 17:22 UTC, bereg6 commented on index.js
> +  console.log(height);
Сорян завтикав.

2022-05-23 17:22 UTC, merged