Footer
VitaliiHrozynskyi/superhero-shop pull request #3
Opened 2022-05-21 09:29 UTC by MayaPrykhodko

Доброго дня. Подивіться, будь-ласка, завдання з footer з врахуванням 3 комміта. При виборі адаптації footer selectable не на всіх нормально відображається

2022-05-22 12:20 UTC, VitaliiHrozynskyi requested changes
Виправте помилки. Вони у вас повторюються по коду, я можливо десь схожі помилки не відмітив, так що передевіться весь код.

Зауваження:
1. Не робіть внутрішні блоки, поки не зробили зовнішні. Судячи з того, що у вас `footer__menu`  був перед `menu` ви його стилізували вже після повної стилізації контенту `footer__info` - так не треба робити.
2. При верстці блоків, концентруйтесь на функціоналі конкретного блоку, у вас присутні стилі, які за логікою мають належати батьківським блокам.

2022-05-22 12:20 UTC, VitaliiHrozynskyi commented on style.css
> +  .icons {
може краще щось типу `footer-icons` або `social-icons`?

2022-05-22 12:20 UTC, VitaliiHrozynskyi commented on style.css
> +  .content {
Уникайте широковживаних назв класів. `content` у вас може бути не тільки у футері.

2022-05-22 12:20 UTC, VitaliiHrozynskyi commented on tech/tech.html
> +    <meta charset="UTF-8" />
Форматування не входило у вашу задачу.

2022-05-22 12:20 UTC, VitaliiHrozynskyi commented on tech/tech.html
> +
Не входило в задачу.

2022-05-22 12:20 UTC, VitaliiHrozynskyi commented on tech/tech.html
> -      <div class="techBlock"><div class="button button--full selectable">my button</div></div>
форматування не входило в задачу.

2022-05-22 12:20 UTC, VitaliiHrozynskyi commented on tech/tech.html
> +    <div class="container">
блок контейнер напряму не відноситься до футера - видалити.

2022-05-22 12:20 UTC, VitaliiHrozynskyi commented on tech/tech.html
> +            <div class="instagram">
тут верстка іконки інстаграма. Має бути відповідна назва:
1 варіант - `<div class="icon-instagram"></div>` маєте конкретний блок іконки інстаграма.
2 варіант - `<div class="icon icon_instagram"></div>` маєте блок `icon` з описом спільних для всіх іконок властивостей і модифікатор `icon_instagram` що вказує саме на іконку інстаграму(по суті просто фон міняє).
3 варіант - `<div class="image-icon"><img src="instagramIconPath" /></div>` - блок іконок-зображень, в якому описується стилі іконки, з самою іконкою всередині.

2022-05-22 12:20 UTC, VitaliiHrozynskyi commented on style.css
> +  margin: 3.75px;
блоки не мають власного вирівнювання\позиціонування

2022-05-22 12:20 UTC, VitaliiHrozynskyi commented on style.css
> +.company {
Уникайте широковживаних назв класів, використайте префікс для конкретизації.

2022-05-22 12:20 UTC, VitaliiHrozynskyi commented on style.css
> +  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
шрифт тексу для цього блоку не унікальний.

2022-05-22 12:20 UTC, VitaliiHrozynskyi commented on style.css
> +.company__title {
Всі колонки меню - абсолютно однакові.
Використайте спільний клас, щоб уникати повторення.

2022-05-22 12:20 UTC, VitaliiHrozynskyi commented on style.css
> +  width: 80%;
Прибрати фіксовану висоту\ширину.

2022-05-22 12:20 UTC, VitaliiHrozynskyi commented on style.css
> +  flex-direction: row;
`flex-direction`  має `row` по замовчуванню.

2022-05-22 12:20 UTC, VitaliiHrozynskyi commented on style.css
> +  border: 1px solid;
не відповідає дизайну.

2022-05-22 12:20 UTC, VitaliiHrozynskyi commented on style.css
> +  padding-right: 10%;
Прибрати паддінги, вони будуть задаватись зовнішнім блоком\обгорткою.

2022-05-22 12:20 UTC, VitaliiHrozynskyi commented on style.css
> +  background: rgba(255, 255, 255, 0);
зайві стилі.

2022-05-22 12:20 UTC, VitaliiHrozynskyi commented on style.css
> +.container {
зайвий блок

2022-05-22 20:57 UTC, MayaPrykhodko commented on style.css
> +.container {
Чому контейнер для footer зайвий? Я розмір footer прописую по відношенню до контейнера
.container {
  display: flex;
  justify-content: center;
  border: 1px solid;
}

.footer {
  display: flex;
  height: 347px;
  flex-basis: 1080px;
  margin: 0px 20px;
}

2022-05-22 21:13 UTC, VitaliiHrozynskyi commented on style.css
> +.container {
Зараз у вас декілька помилок:
1. блок footer залежить від батьківського блоку. 
2. блок footer має стилі вирівнювання.

Зробіть так, щоб футер займав все доступне йому місце по ширині, а висота його залежала від контенту.

розмітка сторінки на блоки буде виконуватись лідом. тобто він вже собі вирішить, як правильно зробити так, щоб контейнер футера був по центру сторінки і мав певну ширину. 

Можливо, його вирівнювання буде 1:1 як і ваше, але то вже інша задача.

2022-05-23 22:44 UTC, VitaliiHrozynskyi requested changes

2022-05-23 22:44 UTC, VitaliiHrozynskyi commented on style.css
> +  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
Не вказуйте стилі шрифта, якщо вони не відрізняються від "основного" на сайті

2022-05-23 22:44 UTC, VitaliiHrozynskyi commented on style.css
> +  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
Не вказуйте стилі шрифта, якщо вони не відрізняються від "основного" на сайті

2022-05-23 22:44 UTC, VitaliiHrozynskyi commented on style.css
> +.logo {
не використовуйте загаліні назви для блоків

2022-05-23 22:44 UTC, VitaliiHrozynskyi commented on style.css
> +.logo {
не використовуйте загаліні назви для блоків

2022-05-23 22:44 UTC, VitaliiHrozynskyi commented on style.css
> +  margin: 89px 0px 22px 0px;
блоки не мають мати стилі вирівнювання

2022-05-23 22:44 UTC, VitaliiHrozynskyi commented on style.css
> +  margin: 89px 0px 22px 0px;
блоки не мають мати стилі вирівнювання

2022-05-23 22:44 UTC, VitaliiHrozynskyi commented on style.css
> +.logo__title {
в блоці лого, немає 'тайтлу' на макеті це просто назва блоку.

тобто у вас в блоці `logo` буде просто лежати зображення.

2022-05-23 22:44 UTC, VitaliiHrozynskyi commented on style.css
> +.logo__title {
в блоці лого, немає 'тайтлу' на макеті це просто назва блоку.

тобто у вас в блоці `logo` буде просто лежати зображення.

2022-05-23 22:44 UTC, VitaliiHrozynskyi commented on style.css
> +  margin-bottom: 26px;
блоки не мають мати вирівнювання

2022-05-23 22:44 UTC, VitaliiHrozynskyi commented on style.css
> +  margin-bottom: 26px;
блоки не мають мати вирівнювання

2022-05-23 22:44 UTC, VitaliiHrozynskyi commented on style.css
> +  margin-bottom: 88px;
те саме, вирівнювання в блоці.

2022-05-23 22:44 UTC, VitaliiHrozynskyi commented on style.css
> +  margin-bottom: 88px;
те саме, вирівнювання в блоці.

2022-05-23 22:44 UTC, VitaliiHrozynskyi commented on style.css
> +.instagram {
додайте іконкам префікс.

2022-05-23 22:44 UTC, VitaliiHrozynskyi commented on style.css
> +.instagram {
додайте іконкам префікс.

2022-05-24 20:35 UTC, VitaliiHrozynskyi requested changes

2022-05-24 20:35 UTC, VitaliiHrozynskyi commented on style.css
> +.footer-logo {
Якщо ви вказали бокс шадоу, то треба вже тоді зробити, щоб зображення завжди розтягувалось на ширину\висоту блоку. 

Додайте стилі .footer-logo img або приберіть тінь

2022-05-24 20:35 UTC, VitaliiHrozynskyi commented on style.css
> +.footer-icons a {
не дуже вдале рішення.

Краще зробити так 
```
<div class="footer-icons">
  <div class="footer-icons__item">
       <a href="#" class="icon icon_instagram"></a>
   </div>
</div>
```
в icon описуєте розмір і положення сображень, модифікатором додаєте саме зображення

2022-05-24 20:35 UTC, VitaliiHrozynskyi commented on style.css
> +.footer__nav a {
Можливо ці стилі краще-б дивились в `footer-menu a`?

2022-05-24 20:35 UTC, VitaliiHrozynskyi commented on style.css
> +.foooter-menu__list  {
може краще footer-menu__item?

І якісь тут дивні стилі...

2022-05-26 02:34 UTC, VitaliiHrozynskyi requested changes
Ці походу останні ;)

2022-05-26 02:34 UTC, VitaliiHrozynskyi commented on style.css
> +@media screen and (max-width:320px) {
в media queries потрібно вказувати тільки зміни. 

якщо у вас в основному блоці вказано, що це flex то заново вказувати не треба ;)

2022-05-26 02:34 UTC, VitaliiHrozynskyi commented on style.css
> +a.icon {
Самі іконки дуже правильно реалізовані, єдине, вони не обов'язкова будуть `a`. 

Також, зараз в них `display: block` береться з `footer-icons a`. тобто в будь якому іншому місці - іконки перестануть бути блочними.

2023-02-11 19:53 UTC, closed without merging