created color-card
VitaliiHrozynskyi/superhero-shop pull request #4
Opened 2022-05-21 10:30 UTC by severlas

2022-05-22 11:40 UTC, VitaliiHrozynskyi requested changes
Стилі та html - на 5.

Але в задачі не вистачає javascript. Колір градієнта має визначатись від зображення.

2022-05-22 11:40 UTC, VitaliiHrozynskyi commented on style.css
> +  border-radius: 10px;
Не варто вказувати внутрішнім елементам бордер радіюс. 

Достатньо зробити `overflow: hidden` для батьківського контейнера.

2022-05-22 11:40 UTC, VitaliiHrozynskyi commented on tech/tech.html
> +      <div class="techBlock">
Коменти - дуже добре ;)

2022-05-22 12:37 UTC, severlas commented on style.css
> +  border-radius: 10px;
Дякую. 
Я потім вже зрозумів, що треба робити з градієнтом, коли подивився кол. Добавлю тоді js та зроблю новий commit.

2022-05-24 20:37 UTC, VitaliiHrozynskyi requested changes

2022-05-24 20:37 UTC, VitaliiHrozynskyi commented on index.js
> +        gradient = document.querySelector('.color-card__gradient'),
Що буде, якщо на сторінці декілька таких блоків?

2022-05-24 20:37 UTC, VitaliiHrozynskyi commented on index.js
> +        color = fac.getColor(document.querySelector('img'));
Якщо на сторінці будуть інші імаги?

2023-10-07 13:14 UTC, closed without merging