heading4_task
VitaliiHrozynskyi/superhero-shop pull request #5
Opened 2022-05-21 11:05 UTC by hazit77

Привіт, перевірь будь ласка і дай фідбек по завданню. Дякую

2022-05-22 11:48 UTC, VitaliiHrozynskyi requested changes
Переробіть код з врахуванням коментарів.

2022-05-22 11:48 UTC, VitaliiHrozynskyi commented on style.css
> +.button {
У вашу задачу на входить форматування коду.

2022-05-22 11:48 UTC, VitaliiHrozynskyi commented on style.css
> +.button--full {
Так само не входить в задачу.

2022-05-22 11:48 UTC, VitaliiHrozynskyi commented on tech/tech.html
> -  <head>
Форматування не входить у вашу задачу.

2022-05-22 11:48 UTC, VitaliiHrozynskyi commented on tech/tech.html
> +    <div class="heading4 selectable">
Не зовсім зрозуміло яку саме задачу ви виконуєте. 

Якщо ваша задача це описати заголовки, то ви маєте в результаті засабмітити 5 блоків з різними класама і стилями до них.

наприклад:
```
<div class="heading1 selectable">тут приклад головного заголовку</div>
<div class="heading2 selectable">тут приклад допоміжного заголовку</div>
...
<div class="heading5 selectable">тут приклад простого заголовку</div>
```

2022-05-22 19:58 UTC, VitaliiHrozynskyi requested changes
Спробуйте внести зміни, якщо будуть проблеми з гітом - пишіть в чат, вирішимо.

2022-05-22 19:58 UTC, VitaliiHrozynskyi commented on style.css
> +  border: 1px solid black;
прибрати ці зміни

2022-05-22 19:58 UTC, VitaliiHrozynskyi commented on tech/tech.html
> -      <div class="techBlock"><div class="button button--full selectable">my button</div></div>
в html досі купа "левих" змін.

Спробуйте відкотитись до початкового стану через "git reset xxx" де xxx -хеш коміту з якого ви починали гілку, зробити новий коміт ТІЛЬКИ з потрібними змінами і потім зробити форс пуш.

2022-05-22 19:58 UTC, VitaliiHrozynskyi commented on tech/tech.html
> +      <h1 class="title-name">Yoann TERUEL</h1>
не потрібно класти `h1` в середину `heading1`.

зробіть просто:
```
<div class="heading1">heading1 example</div>
...
<div class="heading5">heading5 example</div>
```

2022-05-22 19:58 UTC, VitaliiHrozynskyi commented on style.css
> +.title-name,
Всі ці блоки лишні, у вашому коді мають бути тільки стилі для блоків 

heading(1-5)

2022-05-23 14:32 UTC, VitaliiHrozynskyi requested changes

2022-05-23 14:32 UTC, VitaliiHrozynskyi commented on style.css
> +  margin-bottom: 16px;
Блок не має мати вирівнювань.

2022-05-23 14:32 UTC, VitaliiHrozynskyi commented on style.css
> +  display: inline-block;
навіщо тут інлайн блок?

2022-05-23 14:32 UTC, VitaliiHrozynskyi commented on style.css
> +  margin-bottom: 10px;
навіщо відступи та підкреслення? В дизайні ніби нема

2022-05-23 14:38 UTC, hazit77 commented on style.css
> +  display: inline-block;
Інлайн блок зробив, щоб підкреслення було таке ж як довжина тексту

2022-05-23 14:43 UTC, hazit77 commented on style.css
> +  margin-bottom: 10px;
надіслав в телеграм скрін завдання яке видав бот і скрін того що на мою думку в макеті

2022-05-23 15:05 UTC, VitaliiHrozynskyi commented on style.css
> +  margin-bottom: 10px;
Ви не правильно зрозуміли задачу. Вам потрібно ТІЛЬКИ заголовки зверстати )

2022-05-23 15:06 UTC, VitaliiHrozynskyi commented on style.css
> +  margin-bottom: 10px;
А блін, зрозумів, там косяк з тим підкреслюванням ))) його там немає бути

2022-05-23 15:15 UTC, hazit77 commented on style.css
> +  margin-bottom: 10px;
зрозумів, тоді забераю підкреслення. і відступи) гарно дякую

2022-05-24 11:29 UTC, merged