footer done
VitaliiHrozynskyi/superhero-shop pull request #7
Opened 2022-05-21 19:10 UTC by svarnyk

Блок footer

2022-05-22 11:54 UTC, VitaliiHrozynskyi requested changes

2022-05-22 11:54 UTC, VitaliiHrozynskyi commented on tech/tech.html
> +          <div class="leftPart">
Краще зробити `footer__leftPart`, або `footer__info`. Адже блок `leftPart` сам по собі не може бути автономним.

2022-05-22 11:54 UTC, VitaliiHrozynskyi commented on tech/tech.html
> +          <div class="rightPart">
Те саме що з leftPart

2022-05-22 11:54 UTC, VitaliiHrozynskyi commented on tech/tech.html
> +            <div class="menu">
тут можливо варто додати префікс, впевнений, що менюшок на сайті може бути більше.

2022-05-22 11:54 UTC, VitaliiHrozynskyi commented on tech/tech.html
> +            <div class="logo">Logo</div>
додати префікс

2022-05-22 11:54 UTC, VitaliiHrozynskyi commented on tech/tech.html
> -      <div class="techBlock"><div class="button button--full selectable">my button</div></div>
Видалення кнопок не входить у вашу задачу.

2022-05-22 11:54 UTC, VitaliiHrozynskyi commented on style.css
> -.button--full{
видалення кнопок не входить у вашу задачу.

2022-05-22 19:51 UTC, VitaliiHrozynskyi requested changes

2022-05-22 19:51 UTC, VitaliiHrozynskyi commented on tech/tech.html
> +              <div class="footer-menu__item">Home</div>
тут мають бути лінки.

2022-05-22 19:51 UTC, VitaliiHrozynskyi commented on tech/tech.html
> +            <div class="footer-logo">Logo</div>
Вставте плейсхолдер(зображення) логотипу

2022-05-22 19:51 UTC, VitaliiHrozynskyi commented on style.css
> +  height: 100px;
обмеження по висоті не потрібне?

2022-05-22 19:51 UTC, VitaliiHrozynskyi commented on style.css
> +  color: black;
текстові стилі в блоці логотипу? Там буде тільки зображення.

2022-05-22 19:51 UTC, VitaliiHrozynskyi commented on style.css
> +  background: #C4C4C4;
Фон не потрібен

2022-05-23 09:22 UTC, svarnyk commented on style.css
> +  height: 100px;
Прибрав height. Додав gap. Забув прибрати закоментнутий рядок з висотою).

2022-05-23 14:37 UTC, VitaliiHrozynskyi requested changes

2022-05-23 14:37 UTC, VitaliiHrozynskyi commented on style.css
> +  cursor: pointer;
логотип має бути обгорнутий в лінк, робити курсор поінтер тут не треба.

2022-05-23 14:37 UTC, VitaliiHrozynskyi commented on style.css
> +  max-width: 100%;
навіщо max-width?

2022-05-23 14:37 UTC, VitaliiHrozynskyi commented on style.css
> +  height: 347px;
тут все таки краще `min-height` на випадок якщо кількість лінків в меню збільшиться.

2022-05-23 14:37 UTC, VitaliiHrozynskyi commented on style.css
> +  background-color: white;
Навіщо вказаний фон?

2022-05-23 14:37 UTC, VitaliiHrozynskyi commented on style.css
> +  width: 300px;
Що буде, якщо додастся 4-та колонка меню?

2022-05-23 16:02 UTC, svarnyk commented on style.css
> +  width: 300px;
прибрав wight, додав gap

2022-05-23 16:10 UTC, VitaliiHrozynskyi requested changes

2022-05-23 16:10 UTC, VitaliiHrozynskyi commented on style.css
> +  width: 100%;
Все одно не розумію, навіщо тут вказувати фіксовано ширину?

2022-05-23 16:10 UTC, VitaliiHrozynskyi commented on style.css
> +  cursor: default;
Це не потрібно. Курсор буде різним, якщо буде лінк.

2022-05-23 17:41 UTC, merged